run:
  timeout: 15m

linters:
  disable-all: true
  enable:
  # default golangci-lint lints
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused

  # additional lints
  - gochecknoinits
  - gofmt
  - revive
  - misspell
  - unparam
